/* Atlas BNCC — static, local-data exploration. No network services. */
(() => {
'use strict';
const $=id=>document.getElementById(id), D=window.BNCC_DATA;
if(!D||!window.d3){$('graph-count').textContent='Não foi possível carregar os arquivos. Confira se a pasta do site foi copiada por completo.';return;}
const N=new Map(D.nodes.map(n=>[n.id,n])), E=D.edges, PRE=E.filter(e=>e.type==='pre_requisito');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const uniq=a=>[...new Set(a)], sorted=a=>a.sort((a,b)=>a.localeCompare(b,'pt-BR'));
const COLORS={LP:'#b29aff',MA:'#ffbf69',MAT:'#ffbf69',CI:'#57d7ad',CNT:'#57d7ad',HI:'#6ec7ff',GE:'#ff8ead',EI:'#c0cbd7'};
const COLOR_DARK={LP:'#653cc7',MA:'#845012',MAT:'#845012',CI:'#117556',CNT:'#117556',HI:'#216994',GE:'#a63862',EI:'#526475'};
const sourceRefs=D.metadata?.source_references||{};
const sourceCode=(sheet,cell)=>[...new Set(String(cell||'').split('+').map(part=>{const key=`${sheet}!${part.trim()}`,row=part.match(/\d+/)?.[0];return sourceRefs.cells?.[key]||sourceRefs.rows?.[`${sheet}#${row}`];}).filter(Boolean))].join(' + ');
const sourceRef=location=>{const value=String(location??''),match=value.match(/^(.+?)!([A-Z]+\d+(?:\+[A-Z]+\d+)*)$/);return match?sourceCode(match[1],match[2])||value:value;};
const sourceText=value=>{let output=String(value??'');const sheets=[...new Set(Object.keys(sourceRefs.rows||{}).map(key=>key.slice(0,key.lastIndexOf('#'))))].sort((a,b)=>b.length-a.length).map(sheet=>sheet.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'));if(!sheets.length)return output;return output.replace(new RegExp(`(${sheets.join('|')})!([A-Z]+\\d+(?:\\+[A-Z]+\\d+)?)`,'g'),(all,sheet,cell)=>sourceCode(sheet,cell)||all);};
const recordLabel=(r,n)=>r.source_kind==='official_bncc'?`${r.sheet} · p. ${r.source_page}`:r.source_kind==='source_review'?r.sheet:`${r.sheet} · ${sourceRefs.rows?.[`${r.sheet}#${r.row}`]||n?.id||'habilidade'}`;
const competencyDescriptions=D.metadata?.competency_descriptions||{};
const competencySourceUrl=D.metadata?.competency_source?.url||D.metadata?.official_source?.url||'';
const institutionalSources=D.metadata?.institutional_sources||{};
const bnccPortalUrl=institutionalSources.bncc?.url||'https://basenacionalcomum.mec.gov.br/';
const reuniaoPortalUrl=institutionalSources.reuniao?.url||'https://www.institutoreuna.org.br/';
const institutionalSourcesHtml=()=>`<span class="institutional-sources">Fontes institucionais: <a href="${esc(bnccPortalUrl)}" target="_blank" rel="noopener noreferrer">BNCC/MEC</a> · <a href="${esc(reuniaoPortalUrl)}" target="_blank" rel="noopener noreferrer">Instituto Reúna</a>.</span>`;
const competencyRefs=n=>uniq((n?.competencies||[]).map(item=>typeof item==='string'?item:item?.id).filter(Boolean));
const competencyCards=(n,raw='')=>{
 const refs=competencyRefs(n);
 if(!refs.length)return raw?`<div class="field-text">${esc(raw)}</div>`:'<p class="small">Não informado na fonte.</p>';
 return `<div class="competency-grid">${refs.map(id=>{const item=competencyDescriptions[id];const parts=String(id).split(' - ');const kind=parts[0]||'BNCC';const number=item?.number||parts.at(-1)||'';const scope=item?.scope||parts.slice(1,-1).join(' - ')||'Competência relacionada';const context=item?.context||scope;const reference=item?.source||item?.source_reference||'';return `<article class="competency-card"><div class="competency-card-top"><span class="competency-id">${esc(kind)} ${esc(number)}</span><span class="competency-kind">${esc(item?.label||'Competência BNCC')}</span></div><strong>${esc(context)}</strong><p>${esc(item?.description||'Descrição oficial não localizada para esta referência.')}</p>${reference?`<small class="competency-reference">Fonte: ${esc(reference)}</small>`:''}</article>`;}).join('')}</div>${competencySourceUrl?`<p class="small competency-source">Descrição oficial consultada na <a href="${esc(competencySourceUrl)}" target="_blank" rel="noopener noreferrer">BNCC do MEC (2018)</a>.</p>`:''}<p class="small competency-source">${institutionalSourcesHtml()}</p>`;
};
const competencyPlainText=n=>competencyRefs(n).map(id=>{const item=competencyDescriptions[id];return item?`${id} — ${item.context||item.scope||''}: ${item.description} [Fonte: ${item.source||'BNCC oficial'}]`:id;}).join('\n');
const recordSource=(r,n)=>r.source_url?`<div class="source-box"><strong>${r.source_kind==='official_bncc'?'Referência oficial':'Revisão da referência'}</strong><p>${esc(sourceText(r.source_note))}</p><a href="${esc(r.source_url)}" target="_blank" rel="noopener noreferrer">${r.source_kind==='official_bncc'?`Consultar BNCC no MEC · p. ${r.source_page}`:'Consultar documento oficial do MEC'}</a>${r.competency_source_url?`<p><a href="${esc(r.competency_source_url)}" target="_blank" rel="noopener noreferrer">Consultar referencial de competências</a></p>`:''}${institutionalSourcesHtml()}${r.candidate_code?`<p>Possível correção, ainda não confirmada: <button class="secondary" data-skill="${r.candidate_code}">${r.candidate_code}</button></p>`:''}</div>`:'';
const unconfirmedFor=id=>(D.unconfirmed_edges||[]).filter(e=>e.source===id||e.target===id);
const group=n=>n.level==='Educação Infantil'?'EI':n.component_code;
const color=n=>COLORS[group(n)]||'#c0cbd7';
const years=n=>n.years.length?n.years.map(x=>x+'º').join(', ')+' ano':n.level==='Educação Infantil'?'Crianças pequenas · grupo 03':'1ª à 3ª série';
const typelabel={pre_requisito:'Pré-requisito',relacionada:'Relacionada na ficha',relacionada_visao_geral:'Relacionada na visão geral',mencao_comentario:'Menção no comentário'};
const IN=new Map(D.nodes.map(n=>[n.id,[]])),OUT=new Map(D.nodes.map(n=>[n.id,[]]));
for(const e of E){IN.get(e.target).push(e);OUT.get(e.source).push(e);}
for(const n of D.nodes)n.search=norm([n.id,n.text,n.component,n.area,...n.themes,...n.records.map(r=>r.objectives)].join(' '));
let state={id:null,view:'network',scope:'global',depth:1,tab:'skill',record:0},historyIds=[],matching=[],listLimit=55,renderNodes=[],renderEdges=[],positions=new Map(),hover=null,simulation=null,zoom={k:1,x:0,y:0},width=600,height=500,raf=0,toastTimer;
const canvas=$('graph'),ctx=canvas.getContext('2d');
const icons=()=>{if(window.lucide)lucide.createIcons({attrs:{'aria-hidden':'true'}});};
const toast=t=>{$('toast').textContent=t;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,3200);};
for(const a of sorted(uniq(D.nodes.map(n=>n.area))))$('area').add(new Option(a,a));
for(const c of sorted(uniq(D.nodes.map(n=>n.component))))$('component').add(new Option(c,c));
for(let y=1;y<=9;y++)$('year').add(new Option(y+'º ano',String(y)));
$('color-legend').innerHTML=[['LP','L. Portuguesa'],['MA','Matemática'],['CI','Ciências'],['HI','História'],['GE','Geografia'],['EI','Ed. Infantil']].map(([k,l])=>`<span><b style="background:${COLORS[k]}"></b>${l}</span>`).join('');

function filters(){return {q:$('search').value,area:$('area').value,component:$('component').value,stage:$('stage').value,year:$('year').value,focal:$('focal').checked};}
function computeMatches(){const f=filters(),terms=norm(f.q).trim().split(/\s+/).filter(Boolean);matching=D.nodes.filter(n=>(!f.area||n.area===f.area)&&(!f.component||n.component===f.component)&&(!f.stage||n.level===f.stage)&&(!f.year||n.years.includes(+f.year))&&(!f.focal||n.focal)&&terms.every(t=>n.search.includes(t))).sort((a,b)=>{const exact=norm(f.q);return (norm(b.id)===exact)-(norm(a.id)===exact)||Number(b.documented)-Number(a.documented)||a.id.localeCompare(b.id);});}
function renderResults(){
 $('result-count').textContent=matching.length;$('filter-summary').textContent=Object.values(filters()).some(Boolean)?'Filtros aplicados':'Todos os conteúdos';
 $('results').innerHTML=matching.slice(0,listLimit).map(n=>`<div role="listitem"><button class="result ${n.id===state.id?'active':''}" data-skill="${n.id}" aria-label="Explorar ${n.id}" style="--node-color:${COLOR_DARK[group(n)]||'#526475'}"><span class="result-top"><span class="dot"></span>${n.id}${n.focal?'<span class="small-tag">Prioritária · AF ★</span>':''}</span><p>${esc(n.text||'Código citado, sem descrição própria na planilha.')}</p><div class="result-meta">${esc(n.component)} · ${esc(years(n))}</div></button></div>`).join('')+(matching.length>listLimit?`<button class="more" id="more-results">Mostrar mais ${Math.min(55,matching.length-listLimit)}</button>`:'');
 if(!matching.length)$('results').innerHTML='<div class="results-empty">Nenhum resultado.<br>Tente um termo mais curto ou remova um filtro.</div>';
 $('more-results')?.addEventListener('click',()=>{listLimit+=55;renderResults();});
}
function adjacent(id,type,dir){return (dir==='in'?IN:OUT).get(id).filter(e=>type.includes(e.type));}
function walk(id,dir,depth){const found=new Map(),seen=new Set([id]);let frontier=[id];for(let step=1;step<=depth;step++){const next=[];for(const v of frontier)for(const e of adjacent(v,['pre_requisito'],dir)){const target=dir==='in'?e.source:e.target;if(!seen.has(target)){seen.add(target);found.set(target,step);next.push(target);}}frontier=next;}return found;}
function selectionGraph(){let ids=new Set(),lanes=new Map();
 if(state.scope==='global'){ids=new Set(matching.map(n=>n.id));}
 else if(state.id){ids.add(state.id);lanes.set(state.id,0);const ancestors=walk(state.id,'in',state.depth),descendants=walk(state.id,'out',state.depth);if($('show-pre').checked||state.view==='chain'){for(const [id,dep]of ancestors){ids.add(id);lanes.set(id,-dep);}for(const [id,dep]of descendants){ids.add(id);if(!lanes.has(id))lanes.set(id,dep);}}
 if(state.view!=='chain')for(const e of [...IN.get(state.id),...OUT.get(state.id)])if((e.type.startsWith('relacionada')&&$('show-rel').checked)||(e.type==='mencao_comentario'&&$('show-mentions').checked)){ids.add(e.source);ids.add(e.target);}
 }
 const allowed=e=>state.view==='chain'?e.type==='pre_requisito':(e.type==='pre_requisito'?$('show-pre').checked:e.type.startsWith('relacionada')?$('show-rel').checked:$('show-mentions').checked);
 // Visual associations are undirected. Combine duplicates while retaining all provenance.
 const uniqueEdges=new Map();for(const e of E){if(!ids.has(e.source)||!ids.has(e.target)||!allowed(e))continue;const kind=e.type.startsWith('relacionada')?'related':e.type==='pre_requisito'?'pre':'mention';const key=kind+'|'+(kind==='related'?[e.source,e.target].sort().join('|'):e.source+'|'+e.target);if(!uniqueEdges.has(key))uniqueEdges.set(key,{source:e.source,target:e.target,kind,evidence:[]});uniqueEdges.get(key).evidence.push(e);}
 return {ids,lanes,edges:[...uniqueEdges.values()]};
}
function updateURL(push=false){const p=new URLSearchParams();if(state.id)p.set('habilidade',state.id);if(state.view!=='network')p.set('visao',state.view);if(state.scope!=='global')p.set('recorte',state.scope);if(state.depth!==1)p.set('distancia',state.depth);const f=filters();for(const k of ['q','area','component','stage','year'])if(f[k])p.set(k,f[k]);if(f.focal)p.set('foco','1');const h=p.toString();if(location.hash.slice(1)!==h)history[push?'pushState':'replaceState'](null,'',location.pathname+location.search+(h?'#'+h:''));}
function readURL(){const p=new URLSearchParams(location.hash.slice(1)),id=p.get('habilidade');state.id=N.has(id)?id:null;state.view=['network','chain','list'].includes(p.get('visao'))?p.get('visao'):'network';state.scope=p.get('recorte')==='local'&&state.id?'local':'global';state.depth=Array.from({length:9},(_,i)=>i+1).includes(+p.get('distancia'))?+p.get('distancia'):1;if(state.view==='chain'&&!state.id)state.view='network';for(const [key,el]of [['q','search'],['area','area'],['component','component'],['stage','stage'],['year','year']])$(el).value=p.get(key)||'';$('focal').checked=p.get('foco')==='1';$('depth').value=state.depth;state.record=0;state.tab='skill';if(id&&!N.has(id))toast('Código não encontrado. Nenhuma habilidade foi substituída automaticamente.');}
function choose(id,{view,scroll=false}={}){if(!N.has(id))return;state.id=id;state.scope='local';if(view)state.view=view;state.record=0;state.tab='skill';historyIds=[...historyIds.filter(x=>x!==id),id].slice(-6);updateURL(true);refresh();if(window.innerWidth<=700){$('sidebar').classList.remove('open');$('filter-toggle').setAttribute('aria-expanded','false');if(scroll)$('detail').scrollIntoView({behavior:'smooth',block:'start'});}}
function relationCards(ids){return sorted(uniq(ids)).map(id=>{const n=N.get(id);return `<button class="relation-item" data-skill="${id}"><b>${id}<span>${n.focal?'Prioritária · AF ★':n.official_status==='unresolved_reference'?'Em revisão':n.documented?'Com ficha':'Referência'}</span></b><p>${esc(n.text||n.component+' · sem ficha própria')}</p></button>`;}).join('')||'<p class="small">Não informado na planilha.</p>';}
function renderDetail(){const el=$('detail-content'),n=N.get(state.id);
 if(!n){el.innerHTML=`<div class="welcome"><div class="welcome-icon"><i data-lucide="mouse-pointer-2"></i></div><span class="eyebrow">UM PONTO DE PARTIDA</span><h2>Escolha uma habilidade.<br>Descubra os caminhos.</h2><p>Cada ponto representa um código. Clique no mapa ou use a busca para entender suas relações.</p><h3>Experimente explorar</h3><button class="starter-card" data-skill="EF05MA01"><strong>EF05MA01 · Matemática</strong><span>Sistema de numeração, suas bases e os próximos passos.</span></button><button class="starter-card" data-skill="EF06GE08"><strong>EF06GE08 · Geografia</strong><span>Uma conexão entre Geografia e Matemática.</span></button><button class="starter-card" data-skill="EF09LP01"><strong>EF09LP01 · Língua Portuguesa</strong><span>Notícias falsas e a transição para o Ensino Médio.</span></button><div class="source-box"><b>Uma base, diferentes leituras</b><br>${D.nodes.length} códigos com ficha: ${D.metadata.confirmed_official_skills} habilidades e ${D.metadata.review_records} referências em revisão.<br>520 fichas foram completadas com a BNCC oficial. Cada relação pode ser conferida na aba <b>Fonte</b>.</div></div>`;icons();return;}
 const r=n.records[state.record]||null,pre=adjacent(n.id,['pre_requisito'],'in'),depend=adjacent(n.id,['pre_requisito'],'out'),related=[...IN.get(n.id),...OUT.get(n.id)].filter(e=>e.type.startsWith('relacionada')),mentions=[...IN.get(n.id),...OUT.get(n.id)].filter(e=>e.type==='mencao_comentario');
 const relatedIds=uniq(related.map(e=>e.source===n.id?e.target:e.source)),classes=r?[r.classification]:[],recordObjectives=r?.objectives||r?.fields?.F?.value||'',recordCompetencies=r?.competencies||r?.fields?.G?.value||'',recordComment=r?.comment||r?.fields?.I?.value||'';
 const issueNotice=n.issues.length?`<div class="notice"><strong>Atenção à fonte:</strong> há ${n.issues.length} registro(s) de inconsistência associado(s) a esta ficha. Consulte a aba Fonte. Os códigos suspeitos não geram conexões confirmadas.</div>`:'';
 el.innerHTML=`<div class="detail-toolbar"><span class="eyebrow">${n.official_status==='unresolved_reference'?'REFERÊNCIA EM REVISÃO':n.level==='Educação Infantil'?'OBJETIVO DE APRENDIZAGEM':'FICHA DA HABILIDADE'}</span><button class="icon-button" id="close-detail" aria-label="Fechar ficha"><i data-lucide="x"></i></button></div><h2 class="detail-code">${n.id}</h2><div class="badges"><span class="badge comp" style="--badge-bg:${color(n)}25;--badge-text:${COLOR_DARK[group(n)]||'#526475'}">${esc(n.component)}</span><span class="badge">${esc(years(n))}</span>${classes.map(c=>`<span class="badge af">${esc(c)}</span>`).join('')}</div>${!n.documented?'<div class="notice">Somente referência: este código é citado, mas a planilha não fornece uma ficha com seu enunciado. Não foi criado um texto substituto.</div>':''}<p class="detail-description">${esc(r?.text||n.text||'Enunciado não disponível nesta fonte.')}</p><div class="detail-actions"><button class="primary" id="see-chain"><i data-lucide="git-branch"></i>Ver caminhos</button><button class="secondary" id="share" aria-label="Copiar link desta habilidade" title="Copiar link"><i data-lucide="link"></i></button><button class="secondary" id="download-note" aria-label="Baixar ficha em PDF" title="Baixar ficha em PDF"><i data-lucide="download"></i></button></div><div class="detail-tabs" role="tablist" aria-label="Conteúdo da ficha">${[['skill','Habilidade'],['connections','Conexões'],['source','Fonte']].map(([id,l])=>`<button role="tab" id="tab-${id}" aria-controls="panel-${id}" aria-selected="${state.tab===id}" data-tab="${id}">${l}</button>`).join('')}</div>
 <section id="panel-skill" role="tabpanel" aria-labelledby="tab-skill" ${state.tab!=='skill'?'hidden':''}>${issueNotice}${n.records.length>1?`<label class="record-picker">Contexto da ficha<select id="record">${n.records.map((v,i)=>`<option value="${i}" ${i===state.record?'selected':''}>${esc(recordLabel(v,n))}</option>`).join('')}</select></label>`:''}${r?`<div class="detail-section"><h3>Campo ou unidade temática</h3><p>${esc(r.theme||'Não informado.')}</p></div><div class="detail-section"><h3>Objetivos de aprendizagem</h3><div class="field-text">${esc(recordObjectives).replace(/\*\*(.*?)\*\*/gs,'<strong>$1</strong>')||'Não informado.'}</div>${n.component==='Matemática'&&!r.source_kind?'<p class="small">Negrito nos objetivos: expectativa de fluência, conforme a orientação do material.</p>':''}</div><div class="detail-section"><h3>Competências relacionadas</h3>${competencyCards(n,recordCompetencies)}</div><details class="detail-section"><summary>Comentários pedagógicos</summary><div class="field-text">${esc(recordComment)||'Não informado.'}</div></details><p class="footer-note">Registro: ${esc(recordLabel(r,n))}. ${r.source_kind==='source_review'?'Referência original preservada para revisão; não representa habilidade oficial.':r.source_kind?'Enunciado e referência oficial separados da orientação pedagógica editorial. AF/AC/EF não foram atribuídos às novas fichas.':'Classificação mantida no contexto da ficha selecionada.'}</p>`:`<div class="detail-section"><h3>Onde este código aparece</h3>${n.mentions.slice(0,12).map(m=>`<p class="small">${esc(sourceRef(m.sheet+'!'+m.cell))}</p>`).join('')}</div>`}</section>
 <section id="panel-connections" role="tabpanel" aria-labelledby="tab-connections" ${state.tab!=='connections'?'hidden':''}><div class="detail-section"><h3 class="section-heading">O que vem antes <span class="pill">${uniq(pre.map(e=>e.source)).length}</span></h3><p class="small">Pré-requisitos diretos declarados na planilha.</p>${relationCards(pre.map(e=>e.source))}</div><div class="detail-section"><h3 class="section-heading">O que depende dela <span class="pill">${uniq(depend.map(e=>e.target)).length}</span></h3>${relationCards(depend.map(e=>e.target))}</div><div class="detail-section"><h3 class="section-heading">Pode ser trabalhado junto <span class="pill">${relatedIds.length}</span></h3><p class="small">Associações das fichas e visões gerais. Não são pré-requisitos por definição.</p>${relationCards(relatedIds)}</div>${mentions.length?`<details class="detail-section"><summary>Menções em comentários (${uniq(mentions.map(e=>e.source===n.id?e.target:e.source)).length})</summary><p class="small">São citações textuais, não dependências confirmadas.</p>${relationCards(mentions.map(e=>e.source===n.id?e.target:e.source))}</details>`:''}<p class="footer-note">A ficha lista todas as relações diretas da habilidade, mesmo quando um filtro do mapa as oculta.</p></section>
 <section id="panel-source" role="tabpanel" aria-labelledby="tab-source" ${state.tab!=='source'?'hidden':''}>${r?recordSource(r,n):''}<p class="footer-note">Relações e fichas originais: BNCC_Foco.xlsx. Complementação dos enunciados: BNCC oficial, MEC, 2018. Cada evidência da planilha informa o código correspondente à origem na habilidade. Relações conferidas contra a planilha; isso não elimina possíveis erros do próprio documento.<br>${institutionalSourcesHtml()}</p>${n.issues.map(i=>`<div class="notice"><strong>${esc(i.type)}</strong><br>${esc(sourceText(i.source))}<br>${esc(sourceText(i.value))}</div>`).join('')}<div class="detail-section"><h3>Evidências das relações</h3>${unconfirmedFor(n.id).length?`<div class="notice"><strong>Relações da planilha em revisão</strong><p>Estas referências envolvem códigos ausentes na BNCC e não integram os caminhos confirmados.</p>${unconfirmedFor(n.id).map(e=>`<p>${esc(e.source)} → ${esc(e.target)} · ${esc(typelabel[e.type])}<br>${esc(e.evidence.map(v=>sourceRef(v.location)).join('; '))}</p>`).join('')}</div>`:''}${[...pre,...depend,...related,...mentions].map(e=>`<details class="source-detail"><summary>${e.source} ${e.type==='pre_requisito'?'→':'·'} ${e.target}<br>${typelabel[e.type]}</summary>${e.evidence.map(v=>`<p>${esc(sourceRef(v.location))}${v.classification?' · '+esc(v.classification):''}</p>`).join('')}</details>`).join('')||'<p class="small">Nenhuma relação explícita extraída.</p>'}</div><details class="source-detail"><summary>Classificações por contexto</summary>${n.classifications.map(c=>`<p><strong>${esc(c.value)} · ${esc(c.role)}</strong>${esc(sourceText(c.source))}</p>`).join('')||'Sem classificação informada.'}</details><details class="source-detail"><summary>Todas as ocorrências (${n.mentions.length})</summary>${n.mentions.map(m=>`<p>${esc(sourceRef(m.sheet+'!'+m.cell))}</p>`).join('')}</details><p class="footer-note"><a href="./dados/Auditoria.md" download>Baixar revisão completa das referências</a></p></section>`;
 $('close-detail').onclick=clearSelection;$('see-chain').onclick=()=>{state.view='chain';state.scope='local';$('show-pre').checked=true;refresh();updateURL(true);};$('record')?.addEventListener('change',e=>{state.record=+e.target.value;renderDetail();});
 $('share').onclick=copyLink;$('download-note').onclick=downloadNote;
 for(const b of el.querySelectorAll('[data-tab]'))b.onclick=()=>{state.tab=b.dataset.tab;renderDetail();$('tab-'+state.tab).focus();};icons();
}
function buildGraph(){simulation?.stop();const selected=selectionGraph();const groups=['LP','MA','CI','HI','GE','EI','MAT','CNT'];const degrees=new Map();for(const e of selected.edges){degrees.set(e.source,(degrees.get(e.source)||0)+1);degrees.set(e.target,(degrees.get(e.target)||0)+1);}
 renderNodes=[...selected.ids].map((id,i)=>{const n=N.get(id),old=positions.get(id),gi=Math.max(0,groups.indexOf(group(n))),angle=gi*2*Math.PI/6;return {id,n,lane:selected.lanes.get(id)||0,x:old?.x??Math.cos(angle)*400+Math.cos(i*2.399)*Math.sqrt(i)*9,y:old?.y??Math.sin(angle)*330+Math.sin(i*2.399)*Math.sqrt(i)*9,r:state.scope==='global'?5+Math.min(5,Math.sqrt(degrees.get(id)||0)):id===state.id?13:9};});
 const byId=new Map(renderNodes.map(n=>[n.id,n]));renderEdges=selected.edges.map(e=>({...e,source:byId.get(e.source),target:byId.get(e.target)}));positions=byId;
 if(state.view==='chain'){
  const lanes=new Map();for(const n of renderNodes){if(!lanes.has(n.lane))lanes.set(n.lane,[]);lanes.get(n.lane).push(n);}for(const [lane,ns]of lanes){ns.sort((a,b)=>a.id.localeCompare(b.id));ns.forEach((n,i)=>{n.x=lane*250;n.y=(i-(ns.length-1)/2)*80;});}
 }else if(renderNodes.length){
  const global=state.scope==='global';simulation=d3.forceSimulation(renderNodes).randomSource(d3.randomLcg(.43)).force('link',d3.forceLink(renderEdges).id(n=>n.id).distance(global?45:130).strength(global?.11:.38)).force('charge',d3.forceManyBody().strength(global?-52:-430)).force('collide',d3.forceCollide().radius(n=>n.r+(global?8:40)).iterations(2)).force('x',d3.forceX(n=>global?Math.cos(Math.max(0,groups.indexOf(group(n)))*Math.PI/3)*430:0).strength(global?.055:.018)).force('y',d3.forceY(n=>global?Math.sin(Math.max(0,groups.indexOf(group(n)))*Math.PI/3)*330:0).strength(global?.055:.018)).stop();
  for(let i=0;i<(global?110:150);i++)simulation.tick();
 }
 $('graph-empty').hidden=renderNodes.length>0;$('graph-count').textContent=`${renderNodes.length} códigos · ${renderEdges.length} conexões visíveis`;
 $('context-note').textContent=state.view==='chain'?'Caminhos mostram apenas pré-requisitos explícitos. Cada etapa é uma ligação, não um ano escolar.':state.scope==='local'?'A vizinhança inclui bases e dependentes até a distância escolhida, além das associações diretas. Os filtros restringem a busca, sem apagar vizinhos necessários.':'As cores identificam componentes. As linhas representam relações documentadas. Aproxime o mapa ou selecione uma habilidade para ler os códigos.';
 $('graph-instruction').textContent=state.view==='chain'?'Leia da esquerda para a direita: base → habilidade dependente.':state.id?'Clique em outra habilidade para continuar explorando.':'Clique em um ponto para descobrir suas conexões.';
 fit();
}
function size(){const r=$('graph-shell').getBoundingClientRect();width=Math.max(1,r.width);height=Math.max(1,r.height);const dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);draw();}
function fit(){if(!renderNodes.length){zoom={k:1,x:width/2,y:height/2};draw();return;}const xs=renderNodes.map(n=>n.x),ys=renderNodes.map(n=>n.y),xmin=Math.min(...xs)-70,xmax=Math.max(...xs)+70,ymin=Math.min(...ys)-45,ymax=Math.max(...ys)+70;
 const legendSpace=!$('legend').hidden&&width>650?150:0;const availW=Math.max(200,width-100-legendSpace),availH=Math.max(180,height-145);const k=Math.min(state.scope==='global'?1.25:1.5,availW/Math.max(150,xmax-xmin),availH/Math.max(150,ymax-ymin));zoom={k:Math.max(.08,k),x:(width+legendSpace)/2-(xmin+xmax)/2*k,y:(height+40)/2-(ymin+ymax)/2*k};draw();}
function schedule(){if(!raf)raf=requestAnimationFrame(()=>{raf=0;draw();});}
	function draw(){ctx.save();ctx.setTransform(Math.min(devicePixelRatio||1,2),0,0,Math.min(devicePixelRatio||1,2),0,0);ctx.fillStyle='#f7f9fc';ctx.fillRect(0,0,width,height);ctx.fillStyle='#e4e9f1';for(let x=18;x<width;x+=25)for(let y=18;y<height;y+=25){ctx.beginPath();ctx.arc(x,y,.7,0,Math.PI*2);ctx.fill();}
 const selectedId=hover?.id||state.id,neighbors=new Set(selectedId?[selectedId]:[]);if(selectedId)for(const e of renderEdges)if(e.source.id===selectedId||e.target.id===selectedId){neighbors.add(e.source.id);neighbors.add(e.target.id);}
 const screen=n=>({x:n.x*zoom.k+zoom.x,y:n.y*zoom.k+zoom.y}),radius=n=>Math.max(state.scope==='global'?3.4:7,n.r*Math.min(zoom.k,1.7));
	 for(const e of renderEdges){if(e.source===e.target)continue;const a=screen(e.source),b=screen(e.target),active=selectedId&&(e.source.id===selectedId||e.target.id===selectedId);ctx.globalAlpha=selectedId?(active?.8:.07):(state.scope==='global'?.22:.52);ctx.strokeStyle=e.kind==='pre'?'#8192ae':e.kind==='related'?'#8668d7':'#aa8652';ctx.lineWidth=active?1.7:1;ctx.setLineDash(e.kind==='related'?[5,4]:e.kind==='mention'?[2,5]:[]);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.setLineDash([]);
  if(e.kind==='pre'&&(state.scope!=='global'||active||zoom.k>1.1)){const angle=Math.atan2(b.y-a.y,b.x-a.x),r=radius(e.target)+3,tx=b.x-Math.cos(angle)*r,ty=b.y-Math.sin(angle)*r;ctx.beginPath();ctx.moveTo(tx,ty);ctx.lineTo(tx-Math.cos(angle-.48)*7,ty-Math.sin(angle-.48)*7);ctx.lineTo(tx-Math.cos(angle+.48)*7,ty-Math.sin(angle+.48)*7);ctx.closePath();ctx.fillStyle=ctx.strokeStyle;ctx.fill();}}
 ctx.globalAlpha=1;
	 if(state.view==='chain'){const lanes=uniq(renderNodes.map(n=>n.lane)).sort((a,b)=>a-b);ctx.font='12px "Segoe UI",sans-serif';ctx.textAlign='center';ctx.fillStyle='#61748a';for(const lane of lanes){const x=lane*250*zoom.k+zoom.x;ctx.fillText(lane<0?'Bases · '+(-lane)+' etapa(s)':lane>0?'Dependentes · '+lane+' etapa(s)':'Habilidade selecionada',x,107);}}
 for(const p of renderNodes){const s=screen(p),r=radius(p);if(s.x< -100||s.y< -50||s.x>width+100||s.y>height+50)continue;ctx.globalAlpha=selectedId&&!neighbors.has(p.id)?.24:1;
  if(p.id===state.id){ctx.beginPath();ctx.arc(s.x,s.y,r+7,0,Math.PI*2);ctx.fillStyle=color(p.n)+'25';ctx.fill();ctx.strokeStyle=color(p.n);ctx.lineWidth=1.5;ctx.stroke();}
	  ctx.beginPath();ctx.arc(s.x,s.y,r,0,Math.PI*2);ctx.fillStyle=p.n.documented?color(p.n):'#eef2f7';ctx.fill();ctx.strokeStyle=color(p.n);ctx.lineWidth=p.n.documented?1:1.5;ctx.setLineDash(p.n.documented?[]:[3,2]);ctx.stroke();ctx.setLineDash([]);
  const show=$('show-labels').checked||p.id===selectedId||state.scope!=='global'||(neighbors.has(p.id)&&selectedId)||zoom.k>1.6;
	  if(show){const text=p.id+(p.n.focal?' ★':''),font=p.id===state.id?'600 13px':'12px';ctx.font=font+' "Segoe UI",sans-serif';ctx.textAlign='center';ctx.textBaseline='top';const tw=ctx.measureText(text).width,ty=s.y+r+8;ctx.fillStyle='#ffffffee';ctx.fillRect(s.x-tw/2-4,ty-2,tw+8,19);ctx.strokeStyle='#d8e0eb';ctx.lineWidth=.6;ctx.strokeRect(s.x-tw/2-4,ty-2,tw+8,19);ctx.fillStyle=p.id===state.id?'#243447':'#52617a';ctx.fillText(text,s.x,ty);}
 }
 ctx.globalAlpha=1;ctx.restore();$('zoom-label').textContent=Math.round(zoom.k*100)+'%';
}
function renderList(){const list=state.scope==='global'?matching:renderNodes.map(p=>p.n).sort((a,b)=>a.id.localeCompare(b.id));$('list-view').innerHTML=list.length?`<table><thead><tr><th>Código</th><th>Habilidade</th><th>Contexto</th></tr></thead><tbody>${list.map(n=>`<tr><td><button data-skill="${n.id}">${n.id}</button>${n.focal?'<small>Prioritária · AF ★</small>':''}</td><td><p>${esc(n.text||'Sem enunciado próprio na planilha.')}</p><small>${esc(n.component)}</small></td><td>${esc(years(n))}<small>${n.official_status==='unresolved_reference'?'Em revisão':n.documented?'Com ficha':'Somente referência'}</small></td></tr>`).join('')}</tbody></table>`:'<p class="results-empty">Nenhuma habilidade neste recorte.</p>';}
function refresh(){computeMatches();renderResults();renderDetail();for(const b of document.querySelectorAll('[data-view]'))b.setAttribute('aria-pressed',String(b.dataset.view===state.view));$('global').setAttribute('aria-pressed',String(state.scope==='global'));$('local').setAttribute('aria-pressed',String(state.scope==='local'));$('local').disabled=!state.id;$('depth').disabled=state.scope==='global';$('clear-selection').hidden=!state.id;$('view-title').textContent=state.id&&state.scope==='local'?state.id+' e suas conexões':filters().area||'Uma visão do conjunto';$('graph-shell').hidden=state.view==='list';$('list-view').hidden=state.view!=='list';$('show-pre').disabled=state.view==='chain';$('show-rel').disabled=state.view==='chain';$('show-mentions').disabled=state.view==='chain';buildGraph();if(state.view==='list')renderList();$('trail').hidden=!historyIds.length;$('trail').innerHTML='Visitadas: '+historyIds.map(id=>`<button data-skill="${id}">${id}</button>`).join('<span>›</span>');icons();}
function clearSelection(){state.id=null;state.scope='global';if(state.view==='chain')state.view='network';updateURL(true);refresh();}
function clearFilters(){for(const id of ['search','area','stage','year','component'])$(id).value='';$('focal').checked=false;listLimit=55;}
function applyFilters(){state.scope='global';if(state.view==='chain')state.view='network';listLimit=55;updateURL();refresh();}
function download(text,name,type){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
const pdfClean=value=>String(value??'').replace(/\r/g,'').replace(/\*\*/g,'').replace(/[→➜]/g,'->').replace(/[–—−]/g,'-').replace(/•/g,'-').replace(/★/g,'*').replace(/·/g,' - ').replace(/\u00a0/g,' ');
const pdfRgb=hex=>{const value=hex.replace('#','');return [parseInt(value.slice(0,2),16),parseInt(value.slice(2,4),16),parseInt(value.slice(4,6),16)];};
function createSkillPdf(n){
 const Pdf=window.jspdf?.jsPDF;if(!Pdf){toast('O gerador de PDF não carregou. Recarregue a página e tente novamente.');return null;}
	 const doc=new Pdf({unit:'mm',format:'a4',orientation:'portrait'}),left=18,right=192,width=174,bottom=278,navy=pdfRgb('#243447'),purple=pdfRgb('#6746e8'),ink=pdfRgb('#243447'),muted=pdfRgb('#61748a'),teal=pdfRgb('#17745d');const pre=adjacent(n.id,['pre_requisito'],'in'),depend=adjacent(n.id,['pre_requisito'],'out'),related=[...IN.get(n.id),...OUT.get(n.id)].filter(e=>e.type.startsWith('relacionada')),mentions=[...IN.get(n.id),...OUT.get(n.id)].filter(e=>e.type==='mencao_comentario');let y=20;
	 const edgeId=value=>typeof value==='string'?value:value?.id;const mapKinds={pre:'#8192ae',related:'#8668d7',mention:'#aa8652'};const mapLabels={LP:'Língua Portuguesa',MA:'Matemática',MAT:'Matemática',CI:'Ciências',CNT:'Ciências da Natureza',HI:'História',GE:'Geografia',EI:'Educação Infantil'};
	 const pageHeader=small=>{doc.setFillColor(...navy);doc.rect(0,0,210,small?15:48,'F');doc.setTextColor(255,255,255);doc.setFont('helvetica','bold');doc.setFontSize(small?9:10);doc.text('ATLAS BNCC',left,small?10:14);if(small){doc.setFont('helvetica','normal');doc.setFontSize(8);doc.text(n.id,192,10,{align:'right'});}else{doc.setFontSize(8);doc.setTextColor(202,211,231);doc.text('FICHA DE HABILIDADE E CONEXÕES',left,21);doc.setTextColor(255,255,255);doc.setFontSize(25);doc.text(n.id,left,39);}};
	 const drawPdfMap=()=>{const direct=[...pre,...depend,...related.slice(0,16),...mentions.slice(0,8)],visible=renderNodes?.length&&renderNodes.length<=60&&renderNodes.some(p=>p.id===n.id)?renderNodes:null;let mapNodes,mapEdges;if(visible){mapNodes=visible.map(p=>({id:p.id,n:p.n,x:p.x,y:p.y}));mapEdges=renderEdges.filter(e=>e.source?.id&&e.target?.id).map(e=>({source:edgeId(e.source),target:edgeId(e.target),kind:e.kind}));}else{const ids=uniq([n.id,...direct.flatMap(e=>[e.source,e.target])]).filter(Boolean);mapNodes=ids.map((id,i)=>{const item=N.get(id),total=Math.max(1,ids.length-1),angle=(i-1)*Math.PI*2/total,ring=i===0?0:1+(i%3)*.18;return {id,n:item,x:i===0?0:Math.cos(angle)*ring,y:i===0?0:Math.sin(angle)*ring};});mapEdges=direct.map(e=>({source:e.source,target:e.target,kind:e.type==='pre_requisito'?'pre':e.type.startsWith('relacionada')?'related':'mention'}));}
	 const bx=left,by=43,bw=width,bh=152,rawXs=mapNodes.map(p=>p.x),rawYs=mapNodes.map(p=>p.y),xmin=Math.min(...rawXs),xmax=Math.max(...rawXs),ymin=Math.min(...rawYs),ymax=Math.max(...rawYs),sx=(bw-18)/Math.max(1,xmax-xmin),sy=(bh-18)/Math.max(1,ymax-ymin),scale=Math.min(sx,sy),point=p=>({x:bx+9+(p.x-xmin)*scale,y:by+9+(p.y-ymin)*scale});doc.setFillColor(247,249,252);doc.roundedRect(bx,by,bw,bh,3,3,'F');doc.setDrawColor(216,224,235);doc.setLineWidth(.35);doc.roundedRect(bx,by,bw,bh,3,3,'S');const byMapId=new Map(mapNodes.map(p=>[p.id,p]));for(const e of mapEdges){const a=byMapId.get(edgeId(e.source)),b=byMapId.get(edgeId(e.target));if(!a||!b||a.id===b.id)continue;const pa=point(a),pb=point(b),stroke=pdfRgb(mapKinds[e.kind]||mapKinds.related);doc.setDrawColor(...stroke);doc.setLineWidth(a.id===n.id||b.id===n.id?1:.55);if(typeof doc.setLineDashPattern==='function')doc.setLineDashPattern(e.kind==='related'?[1.7,1.2]:e.kind==='mention'?[.6,1.4]:[],0);doc.line(pa.x,pa.y,pb.x,pb.y);if(typeof doc.setLineDashPattern==='function')doc.setLineDashPattern([],0);if(e.kind==='pre'){const angle=Math.atan2(pb.y-pa.y,pb.x-pa.x),r=3.3,tx=pb.x-Math.cos(angle)*r,ty=pb.y-Math.sin(angle)*r;doc.setFillColor(...stroke);doc.triangle(tx,ty,tx-Math.cos(angle-.45)*2.4,ty-Math.sin(angle-.45)*2.4,tx-Math.cos(angle+.45)*2.4,ty-Math.sin(angle+.45)*2.4,'F');}}
	 const degree=new Map();for(const e of mapEdges){degree.set(edgeId(e.source),(degree.get(edgeId(e.source))||0)+1);degree.set(edgeId(e.target),(degree.get(edgeId(e.target))||0)+1);}for(const p of mapNodes){const pointValue=point(p),selected=p.id===n.id,r=selected?4:Math.min(3.1,1.9+(degree.get(p.id)||0)*.12),fill=pdfRgb(color(p.n)||'#c0cbd7'),border=pdfRgb(COLOR_DARK[group(p.n)]||'#526475');doc.setFillColor(...fill);doc.setDrawColor(...border);doc.setLineWidth(selected?1.1:.45);doc.circle(pointValue.x,pointValue.y,r,'FD');if(selected){doc.setDrawColor(...purple);doc.setLineWidth(.7);doc.circle(pointValue.x,pointValue.y,r+2,'S');}const show=selected||mapNodes.length<=22||(degree.get(p.id)||0)>2;if(show){const label=pdfClean(p.id+(p.n.focal?' *':''));doc.setFont('helvetica',selected?'bold':'normal');doc.setFontSize(selected?8:6.6);const tw=doc.getTextWidth(label);doc.setFillColor(255,255,255);doc.setDrawColor(225,230,239);doc.setLineWidth(.2);doc.roundedRect(pointValue.x-tw/2-1.4,pointValue.y+r+1,tw+2.8,4.2,.7,.7,'FD');doc.setTextColor(...ink);doc.text(label,pointValue.x,pointValue.y+r+3.9,{align:'center'});}}
	 doc.setTextColor(...ink);doc.setFont('helvetica','bold');doc.setFontSize(9);doc.text('Mapa de conexões',left,34);doc.setFont('helvetica','normal');doc.setFontSize(7.5);doc.setTextColor(...muted);doc.text(`${n.id} · ${mapNodes.length} habilidades visíveis · relações diretas do recorte`,left,39);let ly=205;doc.setTextColor(...ink);doc.setFont('helvetica','bold');doc.setFontSize(8.5);doc.text('Legenda',left,ly);ly+=7;let lx=left;const groups=uniq(mapNodes.map(p=>group(p.n))).filter(Boolean);for(const key of groups){doc.setFillColor(...pdfRgb(COLORS[key]||'#c0cbd7'));doc.circle(lx+2,ly-1.4,1.7,'F');doc.setTextColor(...muted);doc.setFont('helvetica','normal');doc.setFontSize(7.2);const label=mapLabels[key]||key;doc.text(label,lx+6,ly);lx+=doc.getTextWidth(label)+18;if(lx>left+105){lx=left;ly+=6;}}ly+=7;const relationLegend=[['pre','Pré-requisito'],['related','Relacionada'],['mention','Menção textual']];let rx=left;for(const [kind,label] of relationLegend){doc.setDrawColor(...pdfRgb(mapKinds[kind]));doc.setLineWidth(.8);if(typeof doc.setLineDashPattern==='function')doc.setLineDashPattern(kind==='related'?[1.7,1.2]:kind==='mention'?[.6,1.4]:[],0);doc.line(rx,ly-1.5,rx+10,ly-1.5);if(typeof doc.setLineDashPattern==='function')doc.setLineDashPattern([],0);doc.setTextColor(...muted);doc.setFontSize(7.2);doc.text(label,rx+13,ly);rx+=doc.getTextWidth(label)+28;}ly+=8;doc.setTextColor(...muted);doc.setFontSize(7.2);doc.text('* Habilidade prioritária · AF',left,ly);doc.text('Fontes do mapa: BNCC_Foco.xlsx · Instituto Reúna · BNCC/MEC.',left,ly+5);};
	 const newPage=()=>{doc.addPage();pageHeader(true);y=24;};drawPdfMap();doc.addPage();pageHeader(false);y=61;
 const ensure=height=>{if(y+height>bottom)newPage();};
 const linesFor=(value,size)=>doc.splitTextToSize(pdfClean(value||'Não informado.'),width);
 const writeText=(value,size=10,color=ink,bold=false)=>{const lines=linesFor(value,size),lineH=Math.max(4.3,size*.44);doc.setTextColor(...color);doc.setFont('helvetica',bold?'bold':'normal');doc.setFontSize(size);for(const line of lines){if(y+lineH>bottom)newPage();doc.text(line,left,y);y+=lineH;}y+=2;};
 const writeLink=(label,url)=>{ensure(7);doc.setTextColor(...muted);doc.setFont('helvetica','normal');doc.setFontSize(8);if(typeof doc.textWithLink==='function')doc.textWithLink(pdfClean(label),left,y,{url});else doc.text(pdfClean(label),left,y);y+=5;};
 const section=(title,min=12)=>{ensure(min);doc.setDrawColor(...purple);doc.setLineWidth(.7);doc.line(left,y,left+10,y);doc.setTextColor(...navy);doc.setFont('helvetica','bold');doc.setFontSize(12);doc.text(title,left+14,y+1);y+=9;};
 const badge=(label,x)=>{const text=pdfClean(label),w=doc.getTextWidth(text)+8;doc.setFillColor(236,232,255);doc.roundedRect(x,y-5,w,7,2,2,'F');doc.setTextColor(...purple);doc.setFont('helvetica','bold');doc.setFontSize(8);doc.text(text,x+4,y);return x+w+4;};
 pageHeader(false);y=61;let bx=left;bx=badge(n.component,bx);bx=badge(years(n),bx);for(const c of n.own_classifications||[])bx=badge(c==='AF'?'Habilidade prioritária · AF':c,bx);if(n.official_status==='unresolved_reference')badge('Em revisão',bx);
 y+=9;section(n.level==='Educação Infantil'?'Objetivo de aprendizagem':'Enunciado da habilidade');writeText(n.text||'Enunciado não disponível nesta fonte.',11,ink,false);
 const records=n.records?.length?n.records:[{text:n.text,theme:'',objectives:'',competencies:'',comment:'',sheet:'',row:null}];
 for(const r of records){const objectives=r.objectives||r.fields?.F?.value,competencies=r.competencies||r.fields?.G?.value,comment=r.comment||r.fields?.I?.value,competencyText=competencyPlainText(n)||competencies;section('Contexto: '+recordLabel(r,n));if(r.theme)writeText('Campo ou unidade temática: '+r.theme,10,ink,true);if(objectives){section('Objetivos de aprendizagem');writeText(objectives);}if(competencyText){section('Competências relacionadas');writeText(competencyText);}if(comment){section('Comentários pedagógicos');writeText(comment);}}
 const relation=(title,edges,field)=>{if(!edges.length)return;section(title);for(const e of edges){const evidence=e.evidence?.map(v=>sourceRef(v.location)).filter(Boolean).join('; ');writeText(`${e[field]} - ${typelabel[e.type]||e.type}${evidence?' | Fonte: '+evidence:''}`,9,ink,false);}};
 relation('Pré-requisitos',pre,'source');relation('É pré-requisito para',depend,'target');
 const relatedIds=uniq(related.map(e=>e.source===n.id?e.target:e.source));if(relatedIds.length){section('Pode ser trabalhado junto');writeText(relatedIds.map(id=>{const item=N.get(id),description=item?.text||item?.records?.[0]?.text||'Descrição não disponível na fonte.';return `${id} - ${description}`;}).join('\n'),9);}
 const mentionIds=uniq(mentions.map(e=>e.source===n.id?e.target:e.source));if(mentionIds.length){section('Menções em comentários');writeText(mentionIds.map(id=>id+' - menção textual').join('\n'),9);}
 if(n.issues?.length){section('Atenção à fonte');for(const issue of n.issues)writeText(`${issue.type}: ${sourceText(issue.value)}`,9,ink,false);}
 section('Fontes e referências',30);for(const r of records){writeText(`${recordLabel(r,n)}${r.source_note?': '+sourceText(r.source_note):''}`,9,ink,true);if(r.source_url)writeLink(`Consultar fonte oficial${r.source_page?' - página '+r.source_page:''}`,r.source_url);if(r.competency_source_url)writeLink('Consultar referencial de competências',r.competency_source_url);}writeLink('Portal da Base Nacional Comum Curricular - MEC',bnccPortalUrl);writeLink('Instituto Reúna - Mapas de Foco e referências pedagógicas',reuniaoPortalUrl);
 if(n.mentions?.length){writeText('Ocorrências na planilha: '+uniq(n.mentions.map(m=>sourceRef(m.sheet+'!'+m.cell))).join(', '),8,muted,false);}
 const total=doc.internal.getNumberOfPages();for(let page=1;page<=total;page++){doc.setPage(page);doc.setDrawColor(218,224,234);doc.setLineWidth(.3);doc.line(left,286,192,286);doc.setTextColor(...muted);doc.setFont('helvetica','normal');doc.setFontSize(8);doc.text('Atlas BNCC - fontes: BNCC_Foco.xlsx, BNCC/MEC e Instituto Reúna',left,292);doc.text(`${page} / ${total}`,192,292,{align:'right'});}
 return doc;
}
function downloadNote(){const n=N.get(state.id);if(!n)return;const doc=createSkillPdf(n);if(!doc)return;const name='Atlas-BNCC-'+n.id+'.pdf';if(typeof window.__pdfTestCapture==='function')window.__pdfTestCapture(doc,name);else doc.save(name);toast('PDF da ficha preparado para download.');}
async function copyLink(){updateURL();try{if(location.protocol==='file:'){toast('O link compartilhável funciona depois de publicar o site.');return;}await navigator.clipboard.writeText(location.href);toast('Link da habilidade copiado.');}catch{toast('Copie o endereço da barra do navegador para compartilhar.');}}
function hit(x,y){let best=null,dist=Infinity;for(const n of renderNodes){const d=Math.hypot(n.x*zoom.k+zoom.x-x,n.y*zoom.k+zoom.y-y);if(d<Math.max(13,n.r*zoom.k+5)&&d<dist){best=n;dist=d;}}return best;}
let pointers=new Map(),gesture=null;
canvas.addEventListener('pointerdown',e=>{const r=canvas.getBoundingClientRect(),p={x:e.clientX-r.left,y:e.clientY-r.top};pointers.set(e.pointerId,p);canvas.setPointerCapture(e.pointerId);if(pointers.size===1)gesture={start:p,last:p,moved:false,node:hit(p.x,p.y)};else if(pointers.size===2){const [a,b]=[...pointers.values()];gesture={pinch:true,distance:Math.hypot(a.x-b.x,a.y-b.y),center:{x:(a.x+b.x)/2,y:(a.y+b.y)/2},moved:true};}canvas.classList.add('dragging');});
canvas.addEventListener('pointermove',e=>{const r=canvas.getBoundingClientRect(),p={x:e.clientX-r.left,y:e.clientY-r.top};if(pointers.has(e.pointerId)){pointers.set(e.pointerId,p);if(pointers.size===2){const [a,b]=[...pointers.values()],d=Math.hypot(a.x-b.x,a.y-b.y),center={x:(a.x+b.x)/2,y:(a.y+b.y)/2};if(gesture?.pinch){scale(d/Math.max(1,gesture.distance),center.x,center.y);zoom.x+=center.x-gesture.center.x;zoom.y+=center.y-gesture.center.y;}gesture={pinch:true,distance:d,center,moved:true};}else if(gesture&&!gesture.pinch){const dx=p.x-gesture.last.x,dy=p.y-gesture.last.y;if(Math.hypot(p.x-gesture.start.x,p.y-gesture.start.y)>4)gesture.moved=true;if(gesture.moved){if(gesture.node){gesture.node.x+=dx/zoom.k;gesture.node.y+=dy/zoom.k;}else{zoom.x+=dx;zoom.y+=dy;}}gesture.last=p;}schedule();return;}
 const n=hit(p.x,p.y);if(n!==hover){hover=n;schedule();}canvas.style.cursor=n?'pointer':'grab';const tip=$('graph-tip');tip.hidden=!n;if(n){const text=n.n.text||'Sem ficha própria na planilha.';tip.innerHTML=`<strong>${n.id}${n.n.focal?' ★':''}</strong><p>${n.n.focal?'Habilidade prioritária (AF) · ':''}${esc(n.n.component)}</p><p>${esc(text.slice(0,170))}${text.length>170?'…':''}</p>`;tip.style.left=Math.max(8,Math.min(width-260,p.x+16))+'px';tip.style.top=Math.max(8,Math.min(height-155,p.y+16))+'px';}});
canvas.addEventListener('pointerup',e=>{pointers.delete(e.pointerId);if(!pointers.size){canvas.classList.remove('dragging');const g=gesture;gesture=null;if(g&&!g.moved&&g.node)choose(g.node.id);}});canvas.addEventListener('pointercancel',e=>{pointers.delete(e.pointerId);gesture=null;canvas.classList.remove('dragging');});canvas.addEventListener('pointerleave',()=>{if(!pointers.size){hover=null;$('graph-tip').hidden=true;schedule();}});
function scale(f,x=width/2,y=height/2){const k=Math.max(.06,Math.min(5,zoom.k*f)),ratio=k/zoom.k;zoom.x=x-(x-zoom.x)*ratio;zoom.y=y-(y-zoom.y)*ratio;zoom.k=k;schedule();}
canvas.addEventListener('wheel',e=>{e.preventDefault();const r=canvas.getBoundingClientRect();scale(Math.exp(-e.deltaY*.0015),e.clientX-r.left,e.clientY-r.top);},{passive:false});
$('zoom-in').onclick=()=>scale(1.3);$('zoom-out').onclick=()=>scale(1/1.3);$('fit').onclick=fit;
$('export-image').onclick=()=>{const out=document.createElement('canvas');out.width=Math.max(900,canvas.width);out.height=canvas.height+180;const c=out.getContext('2d');c.fillStyle='#ffffff';c.fillRect(0,0,out.width,out.height);c.drawImage(canvas,0,0);c.fillStyle='#243447';c.font='18px "Segoe UI",sans-serif';c.fillText('Atlas BNCC · '+(state.id||'Mapa geral')+' · '+renderNodes.length+' códigos',24,out.height-135);c.font='14px "Segoe UI",sans-serif';c.fillText('Linha contínua: base → dependente | Tracejada: relacionada | Pontilhada: menção',24,out.height-105);let x=24;for(const [key,label]of [['LP','L. Portuguesa'],['MA','Matemática'],['CI','Ciências'],['HI','História'],['GE','Geografia'],['EI','Ed. Infantil']]){c.fillStyle=COLORS[key];c.beginPath();c.arc(x+5,out.height-76,5,0,Math.PI*2);c.fill();c.fillStyle='#52617a';c.fillText(label,x+17,out.height-71);x+=c.measureText(label).width+40;}c.fillText('Fontes: BNCC_Foco.xlsx e BNCC oficial/MEC · Habilidade prioritária (AF): ★ · Referências inconsistentes em revisão',24,out.height-35);out.toBlob(b=>{const url=URL.createObjectURL(b),a=document.createElement('a');a.href=url;a.download='Atlas-BNCC-'+(state.id||'mapa')+'.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});};
document.addEventListener('click',e=>{const target=e.target.closest('[data-skill]');if(target)choose(target.dataset.skill);});
for(const b of document.querySelectorAll('[data-view]'))b.onclick=()=>{if(b.dataset.view==='chain'&&!state.id){toast('Escolha uma habilidade para ver seus caminhos.');setSidebarTab('filters');$('sidebar').classList.add('open');$('search').focus();return;}state.view=b.dataset.view;if(state.view==='chain'){state.scope='local';$('show-pre').checked=true;}updateURL(true);refresh();};
$('global').onclick=()=>{state.scope='global';if(state.view==='chain')state.view='network';updateURL(true);refresh();};$('local').onclick=()=>{if(state.id){state.scope='local';updateURL(true);refresh();}};$('clear-selection').onclick=clearSelection;$('depth').onchange=()=>{state.depth=+$('depth').value;updateURL();refresh();};
for(const id of ['area','component','stage','year','focal'])$(id).onchange=()=>{if(id==='stage'&&$('stage').value!=='Ensino Fundamental')$('year').value='';applyFilters();};let searchTimer;$('search').addEventListener('input',()=>{clearTimeout(searchTimer);searchTimer=setTimeout(applyFilters,180);});$('reset').onclick=()=>{clearFilters();applyFilters();};
for(const id of ['show-pre','show-rel','show-mentions'])$(id).onchange=()=>{buildGraph();if(state.view==='list')renderList();};$('show-labels').onchange=schedule;
function setLegend(show){$('legend').hidden=!show;$('legend-toggle').setAttribute('aria-expanded',String(show));}
$('legend-toggle').onclick=()=>setLegend($('legend').hidden);$('legend-close').onclick=()=>setLegend(false);
function setSidebarTab(tab){const showSkills=tab==='skills';$('sidebar-filters-panel').hidden=showSkills;$('sidebar-skills-panel').hidden=!showSkills;for(const button of document.querySelectorAll('[data-sidebar-tab]'))button.setAttribute('aria-selected',String(button.dataset.sidebarTab===tab));}
for(const button of document.querySelectorAll('[data-sidebar-tab]'))button.onclick=()=>setSidebarTab(button.dataset.sidebarTab);
$('sidebar-collapse').onclick=()=>{const workspace=document.querySelector('.workspace');workspace.classList.add('sidebar-collapsed');$('sidebar').setAttribute('aria-hidden','true');$('sidebar-restore').hidden=false;$('sidebar-restore').focus();};
$('sidebar-restore').onclick=()=>{const workspace=document.querySelector('.workspace');workspace.classList.remove('sidebar-collapsed');$('sidebar').setAttribute('aria-hidden','false');$('sidebar-restore').hidden=true;$('sidebar-collapse').focus();};
$('filter-toggle').onclick=()=>{setSidebarTab('filters');$('sidebar').classList.toggle('open');$('filter-toggle').setAttribute('aria-expanded',String($('sidebar').classList.contains('open')));if($('sidebar').classList.contains('open'))$('search').focus();};
$('help-open').onclick=()=>$('help').showModal();$('help-close').onclick=()=>$('help').close();$('help-start').onclick=()=>$('help').close();$('help').addEventListener('click',e=>{if(e.target===$('help')){const r=$('help').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('help').close();}});
document.addEventListener('keydown',e=>{if(e.key==='/'&&!/INPUT|TEXTAREA|SELECT/.test(document.activeElement.tagName)){e.preventDefault();setSidebarTab('filters');$('sidebar').classList.add('open');$('search').focus();}});
window.addEventListener('popstate',()=>{readURL();refresh();});window.addEventListener('hashchange',()=>{readURL();refresh();});
new ResizeObserver(()=>{size();if(state.view!=='list')fit();}).observe($('graph-shell'));
readURL();size();refresh();
})();
